apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: europe-west4-docker.pkg.dev/steam-capsule-444320-e6/hello-world-repo/hello-world-service  # Replace with your image name
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        env:
          - name: DB_HOST
            value: 127.0.0.1
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: appdbuser
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-proxy/cloudsql-proxy
        command: ["cloudsql-proxy", "-instances=steam-capsule-444320-e6:us-central1:app-db"]
        env:
          - name: CLOUDSQL_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: my-db-secret
                key: cloud-sql-credentials